### ISSUE TITLE
Fix hotswap choc outline

### ISSUE THREAD

**Issue by perigoso** [perigoso/keyswitch-kicad-library#25]
The current outline used in hotswap choc switches is far for it's real mechanical outline, needs fixing

**Comment by perigoso** [comment]
note: there is a fork that has a pretty good alternative, consider merging.

**Comment by rrotter** [comment]
Thanks for the shoutout. I made a lot of incompatible changes in my fork. I'll cherry-pick the outline changes and send a PR.

**Comment by perigoso** [comment]
That would be great!

**Comment by rrotter** [comment]
Still working on this. I have a new outline that is much better, but it uses `fp_arcs` which aren't supported by PolygoneLine, and they are KiCad 6 `fp_arcs`, which aren't even supported by https://gitlab.com/perigoso/kicad-footprint-generator/.

**Comment by perigoso** [comment]
hm, yeah the footprint generator is still somewhat stuck on kicad 5
