### ISSUE TITLE
License confusion

### ISSUE THREAD

**Issue by ReinBentdal** [perigoso/keyswitch-kicad-library#41]
In GitHub the license is CC-BY while in the library description in KiCad the license is listed as CC-BY-SA-4.0. They should probably be the same?

Github:
https://github.com/perigoso/keyswitch-kicad-library/blob/main/LICENSE-CC-BY-4

KiCad:
<img width="1270" alt="image" src="https://user-images.githubusercontent.com/21336626/167257309-3f64ddd5-b50c-4302-9c40-7aa3ff10f8a3.png">

**Comment by perigoso** [comment]
You are right, there is a mistake here, the intent was to use the same License as the official kicad libraries, which is  CC-BY-SA-4.0
