### ISSUE TITLE
Add switch cutouts

### ISSUE THREAD

**Issue by cgarcia2097** [perigoso/keyswitch-kicad-library#8]
Is it also possible to include switch cutouts in this library, for those interested in rendering one's plates in KiCAD? (IIRC it also supports exporting Edge.Cuts into SVG)

**Comment by perigoso** [comment]
you mean a new footprint with just the cutout outline? its possible sure, just a quick script

**Comment by obra** [comment]
I think that it would be most sensible to do this by picking one of the User layers as the 'plate cutout' layer on every switch footprint.

**Comment by perigoso** [comment]
That is my latest idea, have it on a Eco1 or something, need to find the most switable. this allows the export of a plate dxf directly for a kicad keyboard, which is pretty neat

**Comment by kbrock** [comment]
I'm surprised how

**Comment by perigoso** [comment]
as of now all foot prints that i think are supposed to have cutouts have one on Eco1.User

If any are missing please open a new issue
