### ISSUE TITLE
library importing

### ISSUE THREAD

**Issue by Davides98** [perigoso/keyswitch-kicad-library#9]
I'm new into kicad and I did not understand how to insert this library.

**Comment by perigoso** [comment]
Have you followed the instructions in the Readme?

**Comment by Davides98** [comment]
Yes, I try to insert into preferences --> manage symbol 
pretty files but I can't

**Comment by perigoso** [comment]
This library does not have any symbols, only footprints, different menus

**Comment by Davides98** [comment]
Okay,
I try it.

Footprint Editor -> Footprint Libraries

i didn't understand which folder i need to link inside footprint libraries

Sorry but I'm new into this software

**Comment by perigoso** [comment]
the folders inside `modules/` are the ones you want to select
`Mounting_Keyboard_Stabilizer.pretty`
`Switch_Keyboard_Alps_Matias.pretty`
`Switch_Keyboard_Cherry_MX.pretty`
`Switch_Keyboard_Hybrid.pretty`
`Switch_Keyboard_Kailh.pretty`
